### ISSUE TITLE
I can't install this.

### ISSUE THREAD

**Issue by idgafox** [while1618/endeavouros-setup#1]
When I try to install this setup via github and ../setup.sh, it always locks. It says "/var/lib/db.lck is present." followed by "There may be another Pacman instance running. Waiting...". I waited for over an hour and nothing happened. Is it a common error? cuz i don't have other pacman instances running at the moment, I'm sure.

**Comment by idgafox** [comment]
Just for you to know and add that to your read.me, i fixed using a first eos-update. for some reason, updating first with eos-update was the only way i used to fix it. great work man, keep at it.

**Comment by while1618** [comment]
Hi @idgafox, I just tested the script on clean endeavouros installation and everything worked as expected, I didn't face the pacman problem. It might be worth mentioning that I haven't installed endeavouros apps, so I don't have `eos-update` at all. The issue might be related to some of endeavouros apps, but I'm not sure.

I'll add this issue in the readme, in case anyone else faces it. Thanks for the update on how to fix it.

**Comment by while1618** [comment]
I just test it again with the default installation, so endeavouros apps are installed, and again, it worked fine. I think that this was not related to the setup script, but something just went wrong with the pacman.

Here you can find some useful things regarding this error: [Fixing pacman error](https://www.reddit.com/r/archlinux/comments/sijck2/fixing_pacman_error/)

Also, it worked with `eos-update` because `eos-update` will deal with pacman lock for you: [endeavouros-forum](https://forum.endeavouros.com/t/eos-update-news/52951/4)
